// SUB-SPEC A / #68 — iOS CoreBluetooth radio backend for the pre-session CQ beacon.
//
// LEAVE-BEHIND REFERENCE (not built in CI). talkrypt has no committed iOS app
// target yet; this is a drop-in for one, mirroring the Android `BleBeaconBackend`
// (see android/app/src/main/kotlin/com/talkrypt/app/BleBeacon.kt) — same design,
// CoreBluetooth instead of android.bluetooth. It is written against the uniffi
// Swift bindings that `scripts/build-ios.sh` generates (the `LocalBeaconBackend`
// protocol and the `FfiBeacon` class). It has NOT been compiled or run: there is no
// iPhone here, and the iOS Simulator has no real Bluetooth, so validate it on a
// physical device once an iOS app target exists.
//
// It implements the FFI `LocalBeaconBackend` seam: `advertise(blob:)` publishes a
// GATT service (CBPeripheralManager) carrying the OPAQUE, already-PQ+AES-sealed blob
// on a readable characteristic and advertises the beacon service UUID; scanning
// (CBCentralManager) reads a nearby peer's blob and hands it up so the app can call
// `FfiBeacon.deliverBeacon(blob:source:)`. Non-negotiable invariant, same as every
// backend: it only ever moves opaque sealed bytes — never keys or plaintext.

import CoreBluetooth
import Foundation

// The uniffi Swift bindings declare `protocol LocalBeaconBackend { func advertise(blob: Data); func stop() }`.
// (Generated by scripts/build-ios.sh; import the generated module here in a real target.)

/// Distinct beacon UUIDs — the iOS peer of NearbyDiscovery.BEACON_SERVICE_UUID /
/// BEACON_CHAR_UUID on Android (…0003 / …0004). Kept identical so the two platforms
/// interoperate over the air.
enum TalkryptBeaconUUID {
    static let service = CBUUID(string: "74616C6B-7279-7074-0000-000000000003")
    static let characteristic = CBUUID(string: "74616C6B-7279-7074-0000-000000000004")
}

/// CoreBluetooth implementation of the FFI `LocalBeaconBackend`. Construct one,
/// pass it to `client.startLocalPresence(backend:policy:)`, then call
/// `startScanning` and forward each blob to the returned `FfiBeacon.deliverBeacon`.
final class BleBeaconBackend: NSObject, LocalBeaconBackend {
    private var peripheral: CBPeripheralManager?
    private var central: CBCentralManager?
    private var characteristic: CBMutableCharacteristic?
    private var blob = Data()
    private var pendingAdvertise = false
    private var onBlob: ((Data, String) -> Void)?
    private var seen = Set<UUID>()

    /// The most recent blob passed to `advertise` (mirrors the Android
    /// `lastAdvertised()` used for the emulator spoof self-test).
    private(set) var lastAdvertised: Data?

    // MARK: LocalBeaconBackend (called by talkrypt core)

    func advertise(blob: Data) {
        self.blob = blob
        self.lastAdvertised = blob
        if peripheral == nil {
            peripheral = CBPeripheralManager(delegate: self, queue: nil)
        }
        // Start (or restart) once the manager is powered on (see delegate).
        pendingAdvertise = true
        startAdvertisingIfReady()
    }

    func stop() {
        peripheral?.stopAdvertising()
        peripheral?.removeAllServices()
        central?.stopScan()
        pendingAdvertise = false
        onBlob = nil
        seen.removeAll()
        blob = Data()
    }

    // MARK: Scan side (called by the app; forward to FfiBeacon.deliverBeacon)

    /// Scan for nearby beacons; for each new peripheral, connect and read the opaque
    /// blob, then invoke `onBlob(blob, source)` with a coarse peer handle.
    func startScanning(onBlob: @escaping (Data, String) -> Void) {
        self.onBlob = onBlob
        if central == nil {
            central = CBCentralManager(delegate: self, queue: nil)
        } else {
            central?.scanForPeripherals(withServices: [TalkryptBeaconUUID.service])
        }
    }

    // MARK: internals

    private func startAdvertisingIfReady() {
        guard pendingAdvertise, let pm = peripheral, pm.state == .poweredOn else { return }
        pm.stopAdvertising()
        pm.removeAllServices()
        let ch = CBMutableCharacteristic(
            type: TalkryptBeaconUUID.characteristic,
            properties: [.read],
            value: nil, // dynamic — served in didReceiveRead so the blob can change
            permissions: [.readable]
        )
        characteristic = ch
        let service = CBMutableService(type: TalkryptBeaconUUID.service, primary: true)
        service.characteristics = [ch]
        pm.add(service)
        pm.startAdvertising([CBAdvertisementDataServiceUUIDsKey: [TalkryptBeaconUUID.service]])
    }

    private var connecting: [UUID: CBPeripheral] = [:]
}

// MARK: - Peripheral (advertise + GATT server)

extension BleBeaconBackend: CBPeripheralManagerDelegate {
    func peripheralManagerDidUpdateState(_ pm: CBPeripheralManager) {
        if pm.state == .poweredOn { startAdvertisingIfReady() }
    }

    func peripheralManager(_ pm: CBPeripheralManager, didReceiveRead request: CBATTRequest) {
        guard request.characteristic.uuid == TalkryptBeaconUUID.characteristic else {
            pm.respond(to: request, withResult: .attributeNotFound); return
        }
        // Serve the requested slice (ATT read-blob), so a beacon larger than one MTU
        // is delivered in full.
        guard request.offset <= blob.count else {
            pm.respond(to: request, withResult: .invalidOffset); return
        }
        request.value = blob.subdata(in: request.offset..<blob.count)
        pm.respond(to: request, withResult: .success)
    }
}

// MARK: - Central (scan + read)

extension BleBeaconBackend: CBCentralManagerDelegate, CBPeripheralDelegate {
    func centralManagerDidUpdateState(_ cm: CBCentralManager) {
        if cm.state == .poweredOn {
            cm.scanForPeripherals(withServices: [TalkryptBeaconUUID.service])
        }
    }

    func centralManager(_ cm: CBCentralManager, didDiscover peripheral: CBPeripheral,
                        advertisementData: [String: Any], rssi RSSI: NSNumber) {
        guard seen.insert(peripheral.identifier).inserted else { return }
        connecting[peripheral.identifier] = peripheral // retain during connection
        peripheral.delegate = self
        cm.connect(peripheral)
    }

    func centralManager(_ cm: CBCentralManager, didConnect peripheral: CBPeripheral) {
        peripheral.discoverServices([TalkryptBeaconUUID.service])
    }

    func peripheral(_ peripheral: CBPeripheral, didDiscoverServices error: Error?) {
        guard let svc = peripheral.services?.first(where: { $0.uuid == TalkryptBeaconUUID.service }) else {
            central?.cancelPeripheralConnection(peripheral); return
        }
        peripheral.discoverCharacteristics([TalkryptBeaconUUID.characteristic], for: svc)
    }

    func peripheral(_ peripheral: CBPeripheral, didDiscoverCharacteristicsFor service: CBService, error: Error?) {
        if let ch = service.characteristics?.first(where: { $0.uuid == TalkryptBeaconUUID.characteristic }) {
            peripheral.readValue(for: ch)
        } else {
            central?.cancelPeripheralConnection(peripheral)
        }
    }

    func peripheral(_ peripheral: CBPeripheral, didUpdateValueFor characteristic: CBCharacteristic, error: Error?) {
        if error == nil, let data = characteristic.value, !data.isEmpty {
            // Opaque bytes → hand up for core to open. `source` is coarse (never an identity).
            onBlob?(data, peripheral.identifier.uuidString)
        }
        central?.cancelPeripheralConnection(peripheral)
        connecting[peripheral.identifier] = nil
    }
}
