// #68 mesh messaging — iOS CoreBluetooth Meshtastic node backend.
//
// LEAVE-BEHIND REFERENCE (not built in CI). talkrypt has no committed iOS app
// target yet; this is a drop-in for one, the peer of Android's
// `MeshtasticBleBackend` (android/app/src/main/kotlin/com/talkrypt/app/MeshtasticBle.kt)
// — same design, CoreBluetooth instead of android.bluetooth. Written against the
// uniffi Swift bindings `scripts/build-ios.sh` generates (the `MeshNodeBackend`
// protocol, `FfiMeshNode`, and the free functions `meshtasticEncodeToradio` /
// `meshtasticParseFromradio`). NOT compiled or run here (no iPhone; the iOS
// Simulator has no real Bluetooth) — validate on a physical device + a Meshtastic
// node once an iOS app target exists.
//
// It lets a phone carry talkrypt chat over a Meshtastic LoRa node via BLE: talkrypt
// core hands `send(channel:payload:)` an opaque, already-sealed fragment; we wrap it
// as a PRIVATE_APP `ToRadio` protobuf **using the verified Rust codec over the FFI**
// (never a Swift protobuf) and write it to the node. On the FromNum notification we
// drain FromRadio and hand each recovered PRIVATE_APP payload up so the app can call
// `FfiMeshNode.deliverPacket(...)`. Non-negotiable invariant: opaque sealed bytes
// only — never keys or plaintext.
//
// Over BLE each write is one raw protobuf (GATT frames it — no `0x94 0xC3` Stream
// API framing, which is serial-only); FromRadio is a queue drained by repeated
// reads; FromNum notifies when packets are waiting.

import CoreBluetooth
import Foundation

// The uniffi Swift bindings declare:
//   protocol MeshNodeBackend { func mtu() -> UInt32; func send(channel: UInt8, payload: Data) throws }
//   func meshtasticEncodeToradio(channel: UInt8, payload: Data) -> Data
//   func meshtasticParseFromradio(bytes: Data) -> MeshtasticRxFfi?   // { channel: UInt8; from: UInt32?; payload: Data }
// (Generated by scripts/build-ios.sh; import the generated module in a real target.)

/// Meshtastic BLE GATT UUIDs — verified against meshtastic.org client-api docs and
/// identical to Android's `MeshtasticBleBackend`.
enum MeshtasticUUID {
    static let service = CBUUID(string: "6ba1b218-15a8-461f-9fa8-5dcae273eafd")
    static let toRadio = CBUUID(string: "f75c76d2-129e-4dad-a1dd-7866124401e7")   // write
    static let fromRadio = CBUUID(string: "2c55e69e-4993-11ed-b878-0242ac120002") // read
    static let fromNum = CBUUID(string: "ed9da18c-a800-4f66-a670-aa7547e34453")   // notify
}

/// CoreBluetooth implementation of the FFI `MeshNodeBackend`. Construct one, pass it
/// to `client.startMeshMessaging(backend:channel:)`, then call `startReceiving` and
/// forward each packet to the returned `FfiMeshNode.deliverPacket`.
final class MeshtasticBleBackend: NSObject, MeshNodeBackend {
    private var central: CBCentralManager?
    private var node: CBPeripheral?
    private var toRadioCh: CBCharacteristic?
    private var fromRadioCh: CBCharacteristic?
    private var onPacket: ((UInt8, Data, UInt32?) -> Void)?
    // Fragments queued before the write characteristic is ready.
    private var pendingWrites: [Data] = []

    // MARK: MeshNodeBackend (called by talkrypt core)

    /// Conservative usable `Data.payload` per Meshtastic packet (region/preset dependent).
    func mtu() -> UInt32 { 200 }

    func send(channel: UInt8, payload: Data) throws {
        // The Rust codec wraps the opaque fragment as a PRIVATE_APP ToRadio protobuf.
        let pb = meshtasticEncodeToradio(channel: channel, payload: payload)
        guard let node = node, let ch = toRadioCh else {
            pendingWrites.append(pb) // flushed once connected; core also retries next frame
            return
        }
        node.writeValue(pb, for: ch, type: .withResponse)
    }

    // MARK: connection lifecycle (called by the app; wire onPacket -> FfiMeshNode.deliverPacket)

    /// Connect to the node and start delivering inbound Meshtastic PRIVATE_APP payloads
    /// via `onPacket` (wire it to `FfiMeshNode.deliverPacket`). Call once, after
    /// `client.startMeshMessaging(backend:channel:)` returns the handle.
    func startReceiving(onPacket: @escaping (UInt8, Data, UInt32?) -> Void) {
        self.onPacket = onPacket
        if central == nil {
            central = CBCentralManager(delegate: self, queue: nil)
        }
    }

    func stop() {
        if let node = node { central?.cancelPeripheralConnection(node) }
        node = nil
        toRadioCh = nil
        fromRadioCh = nil
        onPacket = nil
        pendingWrites.removeAll()
    }

    // MARK: internals

    private func flushPending() {
        guard let node = node, let ch = toRadioCh else { return }
        for pb in pendingWrites { node.writeValue(pb, for: ch, type: .withResponse) }
        pendingWrites.removeAll()
    }

    /// Read FromRadio once; the read callback keeps draining until an empty read.
    private func drainFromRadio() {
        guard let node = node, let ch = fromRadioCh else { return }
        node.readValue(for: ch)
    }
}

// MARK: - Central (scan + connect)

extension MeshtasticBleBackend: CBCentralManagerDelegate {
    func centralManagerDidUpdateState(_ cm: CBCentralManager) {
        if cm.state == .poweredOn {
            cm.scanForPeripherals(withServices: [MeshtasticUUID.service])
        }
    }

    func centralManager(_ cm: CBCentralManager, didDiscover peripheral: CBPeripheral,
                        advertisementData: [String: Any], rssi RSSI: NSNumber) {
        cm.stopScan()
        node = peripheral
        peripheral.delegate = self
        cm.connect(peripheral)
    }

    func centralManager(_ cm: CBCentralManager, didConnect peripheral: CBPeripheral) {
        peripheral.discoverServices([MeshtasticUUID.service])
    }
}

// MARK: - Peripheral (characteristics + I/O)

extension MeshtasticBleBackend: CBPeripheralDelegate {
    func peripheral(_ peripheral: CBPeripheral, didDiscoverServices error: Error?) {
        guard let svc = peripheral.services?.first(where: { $0.uuid == MeshtasticUUID.service }) else { return }
        peripheral.discoverCharacteristics(
            [MeshtasticUUID.toRadio, MeshtasticUUID.fromRadio, MeshtasticUUID.fromNum], for: svc)
    }

    func peripheral(_ peripheral: CBPeripheral, didDiscoverCharacteristicsFor service: CBService, error: Error?) {
        for ch in service.characteristics ?? [] {
            switch ch.uuid {
            case MeshtasticUUID.toRadio: toRadioCh = ch
            case MeshtasticUUID.fromRadio: fromRadioCh = ch
            case MeshtasticUUID.fromNum: peripheral.setNotifyValue(true, for: ch) // subscribe
            default: break
            }
        }
        flushPending()   // send anything queued before we were ready
        drainFromRadio() // drain whatever is already queued on the node
    }

    func peripheral(_ peripheral: CBPeripheral, didUpdateValueFor characteristic: CBCharacteristic, error: Error?) {
        switch characteristic.uuid {
        case MeshtasticUUID.fromNum:
            // New packet(s) waiting — drain FromRadio.
            drainFromRadio()
        case MeshtasticUUID.fromRadio:
            guard error == nil, let data = characteristic.value, !data.isEmpty else { return }
            // Opaque protobuf → verified Rust codec extracts a PRIVATE_APP payload.
            if let rx = meshtasticParseFromradio(bytes: data) {
                onPacket?(rx.channel, rx.payload, rx.from)
            }
            drainFromRadio() // keep draining until an empty read
        default:
            break
        }
    }
}
